version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: miPassword123
      MYSQL_DATABASE: miDB
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuarioPass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql-data: